In [4]:
import tensorflow as tf
hello = tf.constant("hello")
sess = tf.Session()
print(sess.run(hello))


b'hello'


In [10]:
round(0.1 + 0.2, 5) == round(0.3, 5)

True

In [17]:
print('*' * 10)
print('\n')
print('*' * 10)

**********


**********


In [20]:
print('집에 있지만', end=' ')
print('집에 가고싶다.')

집에 있지만 집에 가고싶다.


In [ ]:
mark = '*'
n = 10
print(mark + ' 기호를 ' + str(n) + '번 출력')
print(mark * n)

In [45]:
sen = ' is better than '
print('beautiful' + sen + 'ugly')

mark = '*'
print('*'*5)

print('i am %d years old %d' %(12, 3))

x = 1 / 3.0
print('%.3lf' %x)


"{}'s score is{}".format('Jame', 100)


a = 3
b = 12

print('%10d' %a)
print('x%9d' %b)
print('-'*10)
print('%10d' %(a*b))



beautiful is better than ugly
*****
i am 12 years old 3
0.333
         3
x       12
----------
        36


In [55]:
x = 10

if(x > 9) & (x<11):
    print('배가고프다')
else:
    print('진짜다')

배가고프다


In [65]:
y = 1601

if (y%100 == 0) & (y%400 != 0):
    print('평년입니다.')
elif (y%4 == 0):
    print('윤년 입니다.')
else:
    print('윤년도 평년도 아닙니다.')

윤년도 평년도 아닙니다.


In [70]:
def multwo(x):
    y = 2*x
    return y

multwo(10)

20

In [82]:
def EvenOdd(num):
    if num>0:
        if num % 2 == 0:
            return "Even"
        else:
            return "Odd"
    else:
        return "else"
print(EvenOdd(-2))

def f(x):
    return 2*x

f = lambda x: 2*x
    
print(f(2))


else
4


In [100]:

def f(x):
    y = 10*x
    print("y = %d" %y)
    y
    return y

f(10)

y = 999

print(y)

y = 100
999


In [337]:


"""
print(f(10))
print(z)
"""
z = 1

def f(x):
    global z #this
    z = 3
    return z
    
    
f(z)
z

3

In [123]:
for i in range(10):
    for j in range(i):
        print('*', end='')
    print('')
    
    
        


*
**
***
****
*****
******
*******
********
*********


In [125]:
for i in range(4):
    for j in range(4):
        print(i+j, end='')
    print()

0123
1234
2345
3456


In [214]:
x = [1, 2, 3]
y = {'a':1, 'b':2, 'c':3}
y['a']

1

In [218]:
d = [1, 3.14, "pi"]
d[2]

'pi'

In [246]:
e = [[1, 10], [2, 20, 3], [1]]

len(e) #ROW

b = list(range(10))
b = list(range(1, 10))
b

b[0] = 100
b
b.append(900) #add
b

del b[len(b)-1]
b

g = list(range(20))
print(g)
g[-1]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


19

In [267]:
g = list(range(1, 11))
g.append(11)
del g[2]
print(g)
g = g[4:9]
g

g = '999999-1234567'
g[7:13]


[1, 2, 4, 5, 6, 7, 8, 9, 10, 11]


'123456'

In [292]:
a1 = list(range(1, 4))
a2 = list(range(10, 40, 10))
a3 = list(range(100, 400, 50))
list(zip(a1, a2, a3)) #Point(,)?

s=[]
for x, y in zip(a1, a2):
    s.append(x+y)
s

for i, e in enumerate(['a', 'b', 'c']):
    print(i, e)
    

########################################################
for i, (x, y) in enumerate(zip(a1, a2)):
    s[i] = x+y
s


x = [[ 85,  90,  20,  50,  60,  25,  30,  75,  40,  55],
     [ 70, 100,  70,  70,  55,  75,  55,  60,  40,  45],
     [ 25,  65,  15,  25,  20,   5,  60,  70,  35,  10],
     [ 80,  45,  80,  40,  75,  35,  80,  55,  70,  90],
     [ 35,  50,  75,  25,  35,  70,  65,  50,  70,  10]]


sum = 0
count = 0
for i in range(len(x)): #ROW LENGTH(0)
    for j in range(len(x[i])): #COL LENGTH(1)
            sum = sum + x[i][j]
            count = count+1
sum = sum / count
sum

0 a
1 b
2 c


52.7

In [299]:
x = [4, 3, 2, 3, 4]
w = [3, 3, 1, 2, 2]

sum = 0
wsum = 0

for i in range(len(x)):
    sum = sum + w[i]*x[i]
    wsum = wsum + w[i]

sum = sum/wsum
sum

    

3.3636363636363638

In [302]:
a = 2**10
a



1024

In [351]:
"""
h = 10
v = 20

def area(h, v):
    return h*v

a = area(h, v)
print(a)
"""

#얘가 this

class Rectangle(object):
    def __init__(self, h, v):
        self.h = h
        self.v = v
    
    def area(self):
        return self.h * self.v
    
    
class Tri(object):
    def __init__(self, b, h): # Tri()일때는 인자 self만
        self.b = b
        self.h = h
        
    def area(self):
        return (self.b*self.h)/2
    
    def f(self):
        return self.h

r = Rectangle(10, 20)
a = r.area()
print(a)
print(r.area())

#a = Rectangle(1, 1)
#b = Rectangle(2, 2)

#print(a.area())

t1 = Tri(10, 20)

print(t1.f())







200
200
20


In [378]:


class Character(object):
    def __init__(self):
        self.life = 1000
    def attacked(self):
        self.life -=100
        print('공격받음 Hp', self.life)
    def attack(self):
        print('hit')

class Warrior(Character):
    def __init__(self):
        super(Warrior, self).__init__()
        self.strength = 15
        self.intelligence = 5

    def attack(self):
            print("1")
    def attacked(self):
            self.life -= 500
            print('Warrior공격받음 Hp', self.life)
                
class Wizard(Character):
    def __init__(self):
        super(Wizard, self).__init__()
        self.strength = 5
        self.intelligence = 15
    
    def attack(self):
        print("2")
    def attacked(self):        
        self.life -= 100
        print('Wizard공격받음 Hp', self.life)
            
         
a = Warrior()
b = Wizard()
c = Character()

a.attack()
b.attack()

a.attacked()
b.attacked()


class Complex(object):
    def __init__(self, real, imag):
        self.r = real
        self.i = imag

class Complex2(Complex):
    def __repr__(self):
        return "Complex: real=%f, imag=%f" %(self.r, self.i)
    def __str__(self):
        return "[for str] " + self.__repr__()

    
c2 = Complex2(1, 2)
c2

str(c2)


1
2
Warrior공격받음 Hp 500
Wizard공격받음 Hp 900


'[for str] Complex: real=1.000000, imag=2.000000'

In [437]:
class Car(): #인자 Object 클래스 생성안하면 입력도안됨
    def __init__(self):
        self.max_speed = 30
        self.speed = 0
      
    def speed_up(self):
        self.speed += 20
        if(self.speed > self.max_speed):
            self.speed -= 20
            print("overflow speed : %d" %self.speed)
        else:
            print("speed :  %d" % self.speed)
           
        
    def speed_down(self):
        self.speed -= 20
        if(self.speed < 0):
            self.speed += 20
            print("overflow speed : %d" %self.speed)
        else:
            print("speed :  %d" % self.speed)

k = Car()

k.speed_up()
k.speed_up()
k.speed_down()
k.speed_down()

'''
    def overflow(self):
        if (self.speed < 0) | (self.speed > self.max_speed):
            print("overflow")
'''

# 클래스 안에 주석 있으면 안되나..?



speed :  20
overflow speed : 20
speed :  0
overflow speed : 0


In [446]:
import numpy as np
ar = np.array([0, 1, 2, 3])

data = [1, 2, 3, 4]

answer = []

for i in ar:
    answer.append(2*i)
answer


[0, 2, 4, 6]

In [475]:
import numpy as np

a = np.array([10, 20, 30, 40,
             50, 60, 70, 80])
b = np.array([[10, 20, 30, 40],
             [50, 60, 70, 80]])

len(a)
#len(a)

len(b[0])


b[0, 0]

b = np.ones((2, 3))
b.T

print(b.T);
c = np.zeros((3, 2))
print(c);

d = np.hstack((b.T, c)) #horizen인가본데 병합
c = np.vstack((b.T, c))

print(d)
print(c)


[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [515]:
a = np.arange(3)
a

a = np.zeros((2, 3))
a

q = np.arange(3)
w = np.arange(3)
print(np.all(q==w))

#크기다르면 이상한거뜸
#비교

x = np.arange(5)
y = np.ones_like(x)

z = x+y

z.argmin() #최소값위치 index
z[0]=2
# 1/0
print(z)
print(z.mean())
print(np.median(z))


a = np.array([[ 4,  3,  5,  7],
           [ 1, 12, 11,  9],
           [ 2, 15,  1, 14]])

np.sort(a, axis=1) #1번째



True
[2 2 3 4 5]
3.2
3.0


array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])