# Leb4-1

In [5]:
import tensorflow as tf
import numpy as np

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 90.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1], name = 'weight1'))
w2 = tf.Variable(tf.random_normal([1], name = 'weight2'))
w3 = tf.Variable(tf.random_normal([1], name = 'weight3'))
b = tf.Variable(tf.random_normal([1], name = 'bias'))

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(101):
#     sess.run(train) # train에 feed안해줘서 안돌아가는거임
#         print(step, sess.run([cost, hypothesis, train], feed_dict={x1: x1_data,
#                                                                    x2: x2_data,
#                                                                    x3: x3_data,
#                                                                    y: y_data}))
    
    costValue, hyValue, __ = sess.run([cost, hypothesis, train],
                                      feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data,
                                                   y: y_data})
    if step % 10 == 0:
        print(step, costValue, hyValue)
    
    
        
    

0 65.36949 [161.25804 182.78452 185.70651 202.71194 154.59418]
10 28.317947 [155.97054 176.41771 179.44012 195.87659 149.20001]
20 28.163565 [155.97227 176.4113  179.43898 195.86589 149.13725]
30 28.011806 [155.98672 176.42038 179.45297 195.87173 149.08798]
40 27.862339 [156.00096 176.42946 179.46681 195.87755 149.03922]
50 27.715206 [156.01501 176.43854 179.48056 195.88332 148.99097]
60 27.570286 [156.02887 176.4476  179.49416 195.88898 148.94319]
70 27.427582 [156.04253 176.45665 179.50761 195.89458 148.8959 ]
80 27.287024 [156.05597 176.46565 179.5209  195.90009 148.84906]
90 27.14863 [156.06924 176.47467 179.53412 195.90555 148.80273]
100 27.012217 [156.08229 176.48364 179.54713 195.91093 148.75682]


In [6]:
tf.reset_default_graph()

x_data = [[73., 80., 75.], [93., 88., 93.],
          [96., 98., 100.], [89., 91., 90.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])

w = tf.Variable(tf.random_normal([3, 1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")




In [7]:
# 위 식이랑 같음

# hypothesis = x1 * w1 + x2 * w2 + x3* w3 + b
hypothesis = tf.matmul(x, w) + b

In [20]:
cost = tf.reduce_mean(tf.square(hypothesis - y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())


for step in range(101):
    costValue, hyValue, __ = sess.run([cost, hypothesis, train],
                                      feed_dict = {x: x_data,
                                                   y: y_data})
    if step % 10 == 0:
        print(step, "Cost : ", costValue)
        print(hyValue)
        print('\n')




0 Cost :  116.01689
[[154.60988]
 [175.08997]
 [190.14587]
 [178.25761]
 [134.42813]]


10 Cost :  97.5293
[[158.39085]
 [179.65993]
 [195.03392]
 [182.74739]
 [137.92119]]


20 Cost :  97.439285
[[158.389  ]
 [179.68309]
 [195.0434 ]
 [182.75723]
 [137.94626]]


30 Cost :  97.349525
[[158.37576]
 [179.69254]
 [195.03812]
 [182.75357]
 [137.96078]]


40 Cost :  97.2606
[[158.3625 ]
 [179.70187]
 [195.03285]
 [182.74986]
 [137.97525]]


50 Cost :  97.17165
[[158.3493 ]
 [179.71121]
 [195.02753]
 [182.74617]
 [137.98967]]


60 Cost :  97.08349
[[158.33614]
 [179.7205 ]
 [195.02225]
 [182.74246]
 [138.00406]]


70 Cost :  96.99547
[[158.323  ]
 [179.72977]
 [195.01695]
 [182.73878]
 [138.01842]]


80 Cost :  96.90797
[[158.30989]
 [179.739  ]
 [195.01169]
 [182.73512]
 [138.03273]]


90 Cost :  96.82097
[[158.29686]
 [179.74821]
 [195.00644]
 [182.73148]
 [138.047  ]]


100 Cost :  96.734406
[[158.28383]
 [179.75742]
 [195.0012 ]
 [182.72781]
 [138.06125]]


