# Leb6-1

softmax function 확률

In [37]:
import numpy as np
import tensorflow as tf

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x = tf.placeholder("float", [None, 4])
y = tf.placeholder("float", [None, 3])

nb_classes = 3

w = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(x, w) + b)

cost =tf.reduce_mean(-tf.reduce_sum(y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict = {x: x_data, y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={x: x_data, y: y_data}))

    all = sess.run(hypothesis, feed_dict={x: [[1, 11, 7, 9],
                                          [1, 3, 4, 3],
                                          [1, 1, 0, 1]]})
    
    print(all, sess.run(tf.arg_max(all, 1)))
    
#     1
#     0
#     2

0 0.8894128
200 0.35848516
400 0.2667995
600 0.17886978
800 0.15002991
1000 0.13003007
1200 0.11461048
1400 0.10238684
1600 0.09247157
1800 0.08427362
2000 0.077385835
[[1.15257695e-01 8.84742320e-01 3.89903487e-09]
 [3.70118976e-01 6.29480720e-01 4.00352961e-04]
 [1.10498854e-06 9.99944448e-01 5.44757459e-05]] [1 1 1]


# Leb6-2
cross_entropy, one_hot, reshape

### softmax_cross_entropy with logits
### one_hot

cost =tf.reduce_mean(-tf.reduce_sum(y * tf.log(hypothesis), axis=1))

=아래와 동일=

logits = tf.matmul(x, w) + b
hypothesis = tf.nn.softmax(logits)


cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
                                                 labels=y_one_hot)

cost = tf.reduce_mean(cost_i)

In [34]:
tf.reset_default_graph()

xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

nb_classes = 7 # 0-6

x = tf.placeholder(tf.float32, [None, 16])
y = tf.placeholder(tf.int32, [None,1])

y_one_hot = tf.one_hot(y, nb_calsses)
print("one_hot : ", y_one_hot)
y_one_hot = tf.reshape(y_one_hot, [-1, nb_classes])
print("reshape_one_hot : ", y_one_hot)

w = tf.Variable(tf.random_normal([16, nb_classes], name='weight'))
b = tf.Variable(tf.random_normal([nb_classes], name='bias'))


logits = tf.matmul(x, w) + b
hypothesis = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
                                                 labels=y_one_hot)

cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

one_hot :  Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
reshape_one_hot :  Tensor("Reshape:0", shape=(?, 7), dtype=float32)


In [1]:

prediction = tf.argmax(hypothesis, 1) # 0-6값을 하나 택함
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot, 1)) # 제일 큰 수 위치index
accuracy = tf.reduce_mean(tf.cast(correct_prediction, dtype=tf.float32))


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={x: x_data, y: y_data})
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={x: x_data,
                                                             y: y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc:{:.2%}".format(step, loss, acc))
            
# flatten() : [[1][0]] -> [1, 0]

    pred = sess.run(prediction, feed_dict={x: x_data})
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

NameError: name 'tf' is not defined