# Leb7-1
#learning rate 학습률
#정규화

학습률 너무 크게 주게되면 진동하겠지

정규화안하면 값 영향 너무 커서 이상한값 나옴


input = [1 3 2 1 999999 3 2 2]

999값에 영향을 많이 받음

그래서 xy = MinMaxScaler(xy)로 정규화함

In [45]:
import numpy as np
import tensorflow as tf


def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    return numerator / (denominator + 1e-7)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# 주석처리하면 NaN
xy = MinMaxScaler(xy)
print(xy)
print('#'*60)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

x = tf.placeholder(tf.float32, [None, 4])
y = tf.placeholder(tf.float32, [None, 1])
w = tf.Variable(tf.random_normal([4, 1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = tf.matmul(x, w) + b
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(101):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                     feed_dict = {x: x_data, y: y_data})
        print(step, '  Cost : ', cost_val, '\nPrediction: \n', hy_val)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
############################################################
0   Cost :  0.44302392 
Prediction: 
 [[-1.9415313e-01]
 [-1.4152461e-01]
 [ 3.5643578e-05]
 [ 2.4015677e-01]
 [ 1.7260671e-02]
 [ 7.2029650e-02]
 [ 3.0671427e-01]
 [ 5.7025576e-01]]
1   Cost :  0.44300288 
Prediction: 
 [[-1.9412500e-01]
 [-1.4149904e-01]
 [ 5.6624413e-05]
 [ 2.4017262e-01]
 [ 1.7279923e-02]
 [ 7.2048068e-02]
 [ 3.0672517e-01]
 [ 5.7026595e-01]]
2   Cost :  0.4429819 
Prediction: 
 [[-1.9409686e-01]
 [-1.4147353e-01]
 [ 7.7605247e-05]
 [ 2.4018845e-01]

## Accuracy, Prediction 확인

In [ ]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


x = tf.placeholder("float", [None, 3])
y = tf.placeholder("float", [None, 3])
w = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(x, w) + b)
cost = tf.reduce_mean(-tf.reduce_sum(y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, w_val, _ = sess.run([cost, w, optimizer],
                                     feed_dict = {x: x_data, y: y_data})
        print(step, cost_val, w_val)
        
    print("Predicion: ", sess.run(prediction, feed_dict={x: x_test}))
    print("Predicion: ", sess.run(prediction, feed_dict={x: x_test}))
    
    print("Accuracy: ", sess.run(prediction, feed_dict={x: x_test, y: y_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={x: x_test, y: y_test}))
    