# Leb8

#슬라이싱
#shape rank axis

In [27]:
import numpy as np
import pprint as pp


t = np.array([0, 1, 2, 3, 4, 5, 6])

pp.pprint(t)

# 몇 차원인지
print(t.ndim)

# 개수
print(t.shape)

#
print(t[0], t[1], t[-1])

#
print(t[2:5], t[4:-1])

#
print(t[:2], t[3:])


####################

print('#'*20)

t = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(t.ndim)
print(t.shape)

array([0, 1, 2, 3, 4, 5, 6])
1
(7,)
0 1 6
[2 3 4] [4 5]
[0 1] [3 4 5 6]
####################
2
(4, 3)


In [63]:
import tensorflow as tf

sess = tf.Session()
sess.run(tf.global_variables_initializer())

t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval(session=sess)

# axis 는 제일 밖에있는거부터 0++



array([1, 2, 3, 4])

## 행렬곱

In [59]:

matrix1 = tf.constant([[1, 2],
                       [3, 4]])
matrix2 = tf.constant([[1],
                       [2]])
print("1 Shape: ", matrix1.shape)
print("2 Shape: ", matrix2.shape)

print(sess.run(tf.matmul(matrix1, matrix2)), '\n')
print(sess.run(matrix1*matrix2))

1 Shape:  (2, 2)
2 Shape:  (2, 1)
[[ 5]
 [11]] 

[[1 2]
 [6 8]]


## broadcasting
#Shape이 달라도 연산이 됨


In [61]:


matrix1 = tf.constant([1, 2])
matrix2 = tf.constant(3)
                       
print(sess.run(matrix1+matrix2))

[4 5]


In [71]:
x = tf.constant([[1, 2],
                [3, 4]])

tf.reduce_sum(x, axis=-1).eval(session=sess) # =1
tf.reduce_sum(x, axis=0).eval(session=sess)



array([4, 6])

## .argmax()

In [85]:
x = tf.constant([[1, 2],
                [3, 4]])

# 인덱스 반환함
tf.argmax(x, axis=1).eval(session=sess)

array([1, 1], dtype=int64)

## .reshape
## .squeeze
 #늘림
 
## .expand_dims
 #추가

In [106]:
x = tf.constant([[1, 2, 3],
                [4, 5, 3]])
print(x.shape)
tf.reshape(x, shape=[-1, 2]).eval(session=sess)

(2, 3)


array([[1, 2],
       [3, 4],
       [5, 3]])

## .One_hot
#해당 인덱스만 1로

In [107]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=sess)
#이러면 자동적으로 배열안에들어가게됨

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [108]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, [-1, 3]).eval(session=sess)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## .stack

In [109]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]). eval(session=sess)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [113]:
tf.stack([x, y, z], axis = 1).eval(session=sess)

array([[1, 2, 3],
       [4, 5, 6]])

## Ones and Zeros Like
## .ones_like
## .zeros_like

같은 배열 크기의 1이나 0으로 채우고싶을때